from datetime import datetime, timezone

import pytest
from httpx import ASGITransport, AsyncClient

import backend.deps as deps
import backend.main as main
from backend.main import app
from backend.models import TotalLine, TransactionSession
from backend.sales_poller import map_bill_to_transaction


def _sample_bill(bill_no: str = "TEST/PULL/001", *, discount: float = 20.0) -> dict:
    return {
        "nscin": "NSCIN8227",
        "billNo": bill_no,
        "billDate": "2026-04-21",
        "billTime": "11:59:21",
        "billSyncTime": "2026-04-21 11:59:45",
        "cashierDetails": {"cashierName": "Ashbin Adhikari"},
        "consumerName": "Test Customer",
        "billType": "Sale",
        "saleAmt": 470,
        "discAmt": discount,
        "totalDiscAmt": discount,
        "netSaleAmt": 450,
        "taxAmnt": 22.38,
        "roundingAmnt": 0,
        "terminalNo": "POS4",
        "items": [
            {
                "id": "item-001",
                "name": "Non AC Dor 6hrs",
                "productCode": "HAL001",
                "qty": 1,
                "sp": 470,
                "netSP": 450,
                "discount": discount,
            }
        ],
        "payModes": [{"mode": "Phonepe", "tenderCode": "111", "amt": 450, "currency": "INR"}],
        "refundReason": "",
    }


def test_map_bill_to_transaction_uses_sales_shape():
    txn = map_bill_to_transaction(_sample_bill(), deps.config)

    assert txn.id == "POLL-NSCIN8227-TEST-PULL-001"
    assert txn.source == "poll_reconciled"
    assert txn.store_id == "NSCIN8227"
    assert txn.display_pos_label == "POS4"
    assert txn.camera_id == "cam-encalm-01"
    assert txn.bill_number == "TEST/PULL/001"
    assert txn.cashier_id == "Ashbin Adhikari"
    assert txn.items[0].item_description == "Non AC Dor 6hrs"
    assert txn.items[0].discount_type == "AutoGeneratedValue"
    assert txn.payments[0].line_attribute == "UPI"
    assert any(total.line_attribute == "TotalAmountToBePaid" and total.amount == 450 for total in txn.totals)


@pytest.mark.anyio
async def test_history_fetches_and_persists_sales_transactions(monkeypatch):
    async def fake_fetch_historical(days: int):
        return [_sample_bill("TEST/PULL/002")]

    async def fake_fetch_between(start, end):
        return [_sample_bill("TEST/PULL/002")]

    main.sales_poller.api_url = "https://example.com"
    main.sales_poller.api_token = "token"
    monkeypatch.setattr(main.sales_poller, "fetch_historical", fake_fetch_historical)
    monkeypatch.setattr(main.sales_poller, "fetch_between", fake_fetch_between)

    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as client:
        resp = await client.get("/api/history?days=1")

    assert resp.status_code == 200
    payload = resp.json()
    assert payload["ok"] is True
    assert payload["new_transactions"] == 1
    assert any(txn["bill_number"] == "TEST/PULL/002" for txn in payload["transactions"])


@pytest.mark.anyio
async def test_history_skips_bill_when_push_transaction_exists(monkeypatch):
    push_txn = TransactionSession(
        id="push-existing-001",
        store_id="NSCIN8227",
        store_name="Encalm Lounge",
        pos_terminal_no="POS4",
        display_pos_label="POS4",
        cashier_id="cashier-1",
        source="push_assembled",
        status="committed",
        started_at="2026-04-21T11:59:21+00:00",
        committed_at=datetime.now(timezone.utc),
        bill_number="TEST/PULL/003",
        transaction_number="TEST/PULL/003",
        totals=[TotalLine(line_attribute="TotalAmountToBePaid", amount=450.0)],
    )
    deps.storage.append("transactions", push_txn.model_dump())

    async def fake_fetch_historical(days: int):
        return [_sample_bill("TEST/PULL/003")]

    async def fake_fetch_between(start, end):
        return [_sample_bill("TEST/PULL/003")]

    main.sales_poller.api_url = "https://example.com"
    main.sales_poller.api_token = "token"
    monkeypatch.setattr(main.sales_poller, "fetch_historical", fake_fetch_historical)
    monkeypatch.setattr(main.sales_poller, "fetch_between", fake_fetch_between)

    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as client:
        resp = await client.get("/api/history?days=1")
        txns_resp = await client.get("/api/transactions")

    assert resp.status_code == 200
    payload = resp.json()
    assert payload["new_transactions"] == 0

    transactions = txns_resp.json()["transactions"]
    matches = [txn for txn in transactions if txn["bill_number"] == "TEST/PULL/003"]
    assert len(matches) == 1
    assert matches[0]["source"] == "push_assembled"
