import random

PRODUCTS = [
    {"name": "Chicken Burger", "price": 249, "code": "CB001"},
    {"name": "Veg Wrap", "price": 179, "code": "VW002"},
    {"name": "Coke 500ml", "price": 60, "code": "CK003"},
    {"name": "French Fries", "price": 99, "code": "FF004"},
    {"name": "Paneer Tikka", "price": 329, "code": "PT005"},
    {"name": "Masala Dosa", "price": 149, "code": "MD006"},
    {"name": "Filter Coffee", "price": 89, "code": "FC007"},
    {"name": "Biryani", "price": 299, "code": "BR008"},
    {"name": "Samosa", "price": 49, "code": "SM009"},
    {"name": "Ice Cream", "price": 129, "code": "IC010"},
]

CASHIERS = ["EMP-042", "EMP-071", "EMP-103", "EMP-088", "EMP-056"]
PAY_MODES = [("Cash", 0.4), ("CreditCard", 0.3), ("UPI", 0.2), ("Phonepe", 0.1)]

STORES = [
    {"cin": "NDCIN1223", "terminal": "POS 3"},
    {"cin": "NSCIN8227", "terminal": "POS4"},
    {"cin": "NDCIN1227", "terminal": "POS 1"},
    {"cin": "NDCIN1226", "terminal": "POS 2"},
    {"cin": "NDCIN1228", "terminal": "POS 1"},
]


def pick_items(count=None):
    if count is None:
        count = random.randint(1, 5)
    items = random.sample(PRODUCTS, min(count, len(PRODUCTS)))
    return [{"name": p["name"], "price": p["price"], "code": p["code"], "qty": random.randint(1, 3)} for p in items]


def pick_pay_mode():
    modes, weights = zip(*PAY_MODES)
    return random.choices(modes, weights=weights, k=1)[0]


def pick_cashier():
    return random.choice(CASHIERS)


def scenario_manual_entry(items):
    idx = random.randint(0, len(items) - 1)
    items[idx]["scan_attribute"] = "ManuallyEntered"
    return items


def scenario_manual_discount(items, cashier):
    idx = random.randint(0, len(items) - 1)
    items[idx]["discount_type"] = "ManuallyEnteredValue"
    items[idx]["discount"] = round(items[idx]["price"] * 0.3, 2)
    items[idx]["granted_by"] = cashier
    return items


def scenario_high_discount(items):
    idx = random.randint(0, len(items) - 1)
    items[idx]["discount_type"] = "AutoGeneratedPercentage"
    items[idx]["discount"] = round(items[idx]["price"] * 0.35, 2)
    return items


def scenario_void_item(items):
    idx = random.randint(0, len(items) - 1)
    items[idx]["item_attribute"] = "CancellationWithinTransaction"
    return items


def scenario_return_not_recent(items):
    idx = random.randint(0, len(items) - 1)
    items[idx]["item_attribute"] = "ReturnNotRecentlySold"
    return items
